// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt-mONxWgkB1xPs1gQ4B2cIhz9HjuYe6U',
    appId: '1:988240714544:web:a09a58fb78bac5ee8406f5',
    messagingSenderId: '988240714544',
    projectId: 'nathn-expense-tracker-00',
    authDomain: 'nathn-expense-tracker-00.firebaseapp.com',
    storageBucket: 'nathn-expense-tracker-00.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq9_MuFHFPRdhSc54L-n5yGe108oW3EcM',
    appId: '1:988240714544:android:bcef1b4180f7a3d58406f5',
    messagingSenderId: '988240714544',
    projectId: 'nathn-expense-tracker-00',
    storageBucket: 'nathn-expense-tracker-00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFIPjHjLJzc82X4nIt2VYRy3t4yq_tMNM',
    appId: '1:988240714544:ios:cb9c204640d892948406f5',
    messagingSenderId: '988240714544',
    projectId: 'nathn-expense-tracker-00',
    storageBucket: 'nathn-expense-tracker-00.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

}